import {
  Smartphone,
  BarChart,
  Package,
  Building2,
  Users,
  FileText,
  Fingerprint,
  ClipboardList,
  CreditCard,
  MessageSquare,
  Warehouse,
  ScanLine,
  BellRing,
  Truck,
  Table,
  Layers,
  CalendarCheck,
  GraduationCap,
  Key,
  LifeBuoy,
  Gauge,
  Search,
  Accessibility,
  Settings,
  LineChart,
  CloudOff,
  BadgeCheck,
  Bell,
  ShieldCheck,
  Filter,
  Palette,
  Monitor,
  MousePointerClick,
  FlaskConical,
  Server,
  Braces,
  Link,
  MapPin,
  ShoppingCart,
  Lock,
  Repeat,
  PlugZap,
  Map,
  Plug,
  LayoutDashboard,
  ShieldAlert,
  TrendingUp,
  Code2,
  Globe,
  Megaphone,
  Workflow,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  smartphone: Smartphone,
  "bar-chart": BarChart,
  package: Package,
  "building-2": Building2,
  users: Users,
  "file-text": FileText,
  fingerprint: Fingerprint,
  "clipboard-list": ClipboardList,
  "credit-card": CreditCard,
  "message-square": MessageSquare,
  warehouse: Warehouse,
  "scan-line": ScanLine,
  "bell-ring": BellRing,
  truck: Truck,
  table: Table,
  layers: Layers,
  "calendar-check": CalendarCheck,
  "graduation-cap": GraduationCap,
  key: Key,
  "life-buoy": LifeBuoy,
  gauge: Gauge,
  search: Search,
  accessibility: Accessibility,
  settings: Settings,
  "line-chart": LineChart,
  "cloud-off": CloudOff,
  "badge-check": BadgeCheck,
  bell: Bell,
  "shield-check": ShieldCheck,
  filter: Filter,
  palette: Palette,
  monitor: Monitor,
  "mouse-pointer-click": MousePointerClick,
  "flask-conical": FlaskConical,
  server: Server,
  braces: Braces,
  link: Link,
  "map-pin": MapPin,
  "shopping-cart": ShoppingCart,
  lock: Lock,
  repeat: Repeat,
  "plug-zap": PlugZap,
  map: Map,
  plug: Plug,
  "layout-dashboard": LayoutDashboard,
  "shield-alert": ShieldAlert,
  "trending-up": TrendingUp,
  "code-2": Code2,
  globe: Globe,
  megaphone: Megaphone,
  workflow: Workflow,
};

export function getIcon(name: string | null | undefined): LucideIcon {
  if (!name) return Package;
  return iconMap[name] ?? Package;
}

export function renderIcon(name: string | null | undefined, className?: string) {
  const Icon = getIcon(name);
  return <Icon className={className} aria-hidden="true" />;
}
